### ISSUE TITLE
Where is package "edu.psu.cse.siis.coal.lang"?

### ISSUE THREAD

**Issue by fripSide** [siis/coal#1]
The versions of Soot and FlowDroid are too old. I wan to using the newest version to compile a new version of IC3. But I failed to compile coal.
I download the newest source code and try to compile it. And I failed with a error message of "edu.psu.cse.siis.coal.lang.ParseException", "edu.psu.cse.siis.coal.lang.PropagationParser" does not exist.

**Comment by docteau** [comment]
Hi,

These files should be automatically generated by Maven from the grammar file (src/main/javacc/propagation.jj) when you compile the project. What commands did you use to perform the compilation?

Also, I recommend for you to compile the develop branches of both COAL and IC3, since they use a more recent version of Soot and the FlowDroid entry point construction procedure. It would be much easier than integrating your own versions of Soot and FlowDroid.

Best,
Damien
